# --- Schrift ---
font_family               JetBrainsMono Nerd Font Regular
bold_font                 JetBrainsMono Nerd Font Bold
italic_font               JetBrainsMono Nerd Font Italic
bold_italic_font          JetBrainsMono Nerd Font Bold Italic
font_size                 11.0
allow_bold_ext_colors     no
text_composition_strategy legacy

# --- Hintergrund & Transparenz ---
background                 #0E1415
foreground                 #CECECE
background_opacity         0.9
dynamic_background_opacity yes

# --- Cursor ---
cursor                #CECECE
cursor_text_color     #0E1415
cursor_shape          beam
cursor_blink_interval 0.5

# --- Farben ---

# Schwarz
color0  #000000
color8  #777777

# Rot
color1  #e25d56
color9  #f36868

# Grün
color2  #55DD33
color10 #88db3f

# Gelb
color3  #e9bf57
color11 #f0bf7a

# Blau
color4  #3971ed
color12 #3971ed

# Magenta
color5  #915caf
color13 #e987e9

# Cyan
color6  #23acdd
color14 #4ac9e2

# Weiß
color7  #f0f0f0
color15 #FFFFFF

# --- Selektion ---
selection_foreground #0E1415
selection_background #CECECE

# --- Optik ---
window_padding_width 4
window_border_radius 10

# Optional:
# hide_window_decorations yes

# --- Tabs ---
tab_bar_style powerline

active_tab_foreground   #0E1415
active_tab_background   #3971ed

inactive_tab_foreground #CECECE
inactive_tab_background #1a2224

# --- Optik ---
# Entfernt die dicke Titelleiste
#hide_window_decorations yes
# Abstände zum Rand (damit der Text nicht am Rand klebt)
window_padding_width 4
# Abgerundete Ecken (funktioniert nur, wenn der Fenstermanager es erlaubt)
window_border_radius 10
