[window]
opacity = 0.9
dimensions = { columns = 104, lines = 32 }
dynamic_padding = true

[env]
TERM = "xterm-256color"

[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#55DD33'
yellow = '#e9bf57'
blue = '#3971ed'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#3971ed'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'

